# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Device-HUAWEI-E355
version:      0.01
version_from: lib/Device/HUAWEI/E355.pm
installdirs:  site
requires:
    Exporter:                      0
    strict:                        0
    vars:                          0
    XML::TreePP                    0
    XML::String

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
